export default {
  // app
  SET_APP_ERROR_STATUS: 'SET_APP_ERROR_STATUS',

  // phones
  ADD_PHONES: 'ADD_PHONES',
  TOGGLE_PHONES_LOADING: 'TOGGLE_PHONES_LOADING',

  // phone detail
  HIDE_PHONE_DETAIL: 'HIDE_PHONE_DETAIL',
  TOGGLE_PHONE_DETAIL_LOADING: 'TOGGLE_PHONE_DETAIL_LOADING',
  SET_PHONE_DETAIL: 'SET_PHONE_DETAIL'
}
